#location for MSI
$location = "westeurope"

#Define Locking Mode
$lockMode = 'None'  # AllResourcesDoNotDelete | AllResourcesDoNotDelete | AllResourcesReadOnly | None

#parameters for Resource Group
$resourceGroupParams = @{
    name = "d-rgr-core-01"
}

#parameters for artifacts
$params = @{
automationAccount_accountName='d-aut-core-01'
automationAccount_accountType= 'Basic'
keyVault_vaultName = 'd-kva-core-01'
keyVault_sku ='Premium'
keyVault_tenantId= 'a7262e59-1b56-4f5a-a412-6f07181f48ee'
keyVault_userId = 'cfc359db-3d29-460f-b516-f7d00234631e'
logAnalyticsWorkspace_logAnalyticsWorkspaceName = 'd-ala-core-01'
logAnalyticsWorkspace_automationAccountName = 'd-aut-core-01'
SecurityCenter_workspaceName = 'd-ala-core-01'
SecurityCenter_workspaceResourceGroup = 'd-rgr-core-01'
SecurityCenter_subscriptionId = '425d5bb6-f17a-493c-a3fd-885e274b072f'
storageAccountforCloudShell_storageAccountName = 'dstoshell01'
storageAccountforCloudShell_accountType = 'Standard_LRS'
storageAccountforDiagnosticLogs_storageAccountName = 'dstolog01'
storageAccountforDiagnosticLogs_accountType = 'Standard_LRS'
storageAccountforArtifacts_storageAccountName = 'dstoarm01'
StorageAccountforArtifacts_containerName = 'armtemplates'
storageAccountforArtifacts_accountType  = 'Standard_LRS'
activitylogs_subscriptionId = '425d5bb6-f17a-493c-a3fd-885e274b072f'
activitylogs_workspaceName = 'd-ala-core-01'


#base governance Policy Initiative Parameters
requirespecifiedtagonresourcegroups_TAGNAME_1 = "Environment"
requirespecifiedtagonresourcegroups_TAGNAME_2 = "Service"
requirespecifiedtagonresourcegroups_TAGNAME_3 = "OwnerTech"
requirespecifiedtagonresourcegroups_TAGNAME_4 = "OwnerApp"
requirespecifiedtagonresourcegroups_TAGNAME_5 = "Notes"
requirespecifiedtagonresourcegroups_effect_1 = "Deny"
requirespecifiedtagonresourcegroups_effect_2 = "Deny"
requirespecifiedtagonresourcegroups_effect_3 = "Deny"
requirespecifiedtagonresourcegroups_effect_4 = "Deny"
requirespecifiedtagonresourcegroups_effect_5 = "Deny"
appendspecifiedtagfromresourcegroup_TAGNAME_1 = "Environment"
appendspecifiedtagfromresourcegroup_TAGNAME_2 = "Service"
appendspecifiedtagfromresourcegroup_TAGNAME_3 = "OwnerTech"
appendspecifiedtagfromresourcegroup_TAGNAME_4 = "OwnerApp"
appendspecifiedtagfromresourcegroup_TAGNAME_5 = "Notes"
appendspecifiedtagfromresourcegroup_effect_1 = "Append"
appendspecifiedtagfromresourcegroup_effect_2 = "Append"
appendspecifiedtagfromresourcegroup_effect_3 = "Append"
appendspecifiedtagfromresourcegroup_effect_4 = "Append"
appendspecifiedtagfromresourcegroup_effect_5 = "Append"

resourcelocations_LISTOFALLOWEDLOCATIONS_1 = "northeurope","westeurope","switzerlandnorth","switzerlandwest","westus","westus2","eastus","eastus2"
resourcegrouplocations_LISTOFALLOWEDLOCATIONS_1 = "northeurope","westeurope","switzerlandnorth","switzerlandwest","westus","westus2","eastus","eastus2"
allowedvirtualmachineskus = "Standard_B1ms","Standard_B2s","Standard_B2ms","Standard_DS1_v2","Standard_D2s_v3","Standard_D4s_v3","Standard_E2s_v3"
allowedvirtualmachines_effect = "Deny"
allowedstorageaccountskus = "Standard_LRS","Standard_RAGRS","Standard_GRS","Standard_ZRS"
allowedstorageaccountskus_effect = "Deny"
classicresources_effect = "Deny"
resourcelocations_effect = "Deny"
resourcegrouplocations_effect = "Deny"
networkinterfacesshouldnothavepublicipaddresses_effect = "Deny"


#SecurityCenter Policy Parameters
EnableMonitoringinAzureSecurityCenter_vmssSystemUpdatesMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_vmssEndpointProtectionMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_vmssOsVulnerabilitiesMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_systemUpdatesMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_systemConfigurationsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_endpointProtectionMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_diskEncryptionMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_networkSecurityGroupsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_networkSecurityGroupsOnSubnetsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_networkSecurityGroupsOnVirtualMachinesMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_webApplicationFirewallMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_nextGenerationFirewallMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_vulnerabilityAssesmentMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_serverVulnerabilityAssessmentEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_storageEncryptionMonitoringEffect="Audit"
EnableMonitoringinAzureSecurityCenter_jitNetworkAccessMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_adaptiveApplicationControlsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_sqlAuditingMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_sqlEncryptionMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_sqlDbEncryptionMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_sqlServerAuditingMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_sqlServerAuditingActionsAndGroupsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_SqlServerAuditingRetentionDaysMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInAppServiceMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInSelectiveAppServicesMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_encryptionOfAutomationAccountMonitoringEffect="Audit"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInBatchAccountMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInBatchAccountRetentionDays="365"
EnableMonitoringinAzureSecurityCenter_metricAlertsInBatchAccountMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_classicComputeVMsMonitoringEffect="Audit"
EnableMonitoringinAzureSecurityCenter_classicStorageAccountsMonitoringEffect="Audit"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInDataLakeAnalyticsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInDataLakeAnalyticsRetentionDays="365"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInDataLakeStoreMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInDataLakeStoreRetentionDays="Disabled"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInEventHubMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInEventHubRetentionDays="365"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInKeyVaultMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInKeyVaultRetentionDays="365"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInLogicAppsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInLogicAppsRetentionDays="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInRedisCacheMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInSearchServiceMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInSearchServiceRetentionDays="365"
EnableMonitoringinAzureSecurityCenter_aadAuthenticationInServiceFabricMonitoringEffect="Audit"
EnableMonitoringinAzureSecurityCenter_clusterProtectionLevelInServiceFabricMonitoringEffect="Audit"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInServiceBusMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInServiceBusRetentionDays="365"
EnableMonitoringinAzureSecurityCenter_namespaceAuthorizationRulesInServiceBusMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_aadAuthenticationInSqlServerMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_secureTransferToStorageAccountMonitoringEffect="Audit"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInStreamAnalyticsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInStreamAnalyticsRetentionDays="365"
EnableMonitoringinAzureSecurityCenter_useRbacRulesMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_disableUnrestrictedNetworkToStorageAccountMonitoringEffect="Audit"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInServiceFabricMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_accessRulesInEventHubNamespaceMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_accessRulesInEventHubMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_sqlDbVulnerabilityAssesmentMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_sqlDbDataClassificationMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_identityDesignateLessThanOwnersMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_identityDesignateMoreThanOneOwnerMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_identityEnableMFAForOwnerPermissionsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_identityEnableMFAForWritePermissionsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_identityEnableMFAForReadPermissionsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_identityRemoveDeprecatedAccountWithOwnerPermissionsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_identityRemoveDeprecatedAccountMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_identityRemoveExternalAccountWithOwnerPermissionsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_identityRemoveExternalAccountWithWritePermissionsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_identityRemoveExternalAccountWithReadPermissionsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_apiAppConfigureIPRestrictionsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_functionAppConfigureIPRestrictionsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_webAppConfigureIPRestrictionsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_apiAppDisableRemoteDebuggingMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_functionAppDisableRemoteDebuggingMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_webAppDisableRemoteDebuggingMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_apiAppDisableWebSocketsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_functionAppDisableWebSocketsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_webAppDisableWebSocketsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_apiAppEnforceHttpsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_functionAppEnforceHttpsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_webAppEnforceHttpsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_apiAppEnforceHttpsMonitoringEffectV2="Audit"
EnableMonitoringinAzureSecurityCenter_functionAppEnforceHttpsMonitoringEffectV2="Audit"
EnableMonitoringinAzureSecurityCenter_webAppEnforceHttpsMonitoringEffectV2="Audit"
EnableMonitoringinAzureSecurityCenter_apiAppRestrictCORSAccessMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_functionAppRestrictCORSAccessMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_webAppRestrictCORSAccessMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_apiAppUsedCustomDomainsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_functionAppUsedCustomDomainsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_webAppUsedCustomDomainsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_apiAppUsedLatestDotNetMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_webAppUsedLatestDotNetMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_apiAppUsedLatestJavaMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_webAppUsedLatestJavaMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_webAppUsedLatestNodeJsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_apiAppUsedLatestPHPMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_webAppUsedLatestPHPMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_apiAppUsedLatestPythonMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_webAppUsedLatestPythonMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_vnetEnableDDoSProtectionMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInIoTHubMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_diagnosticsLogsInIoTHubRetentionDays="365"
EnableMonitoringinAzureSecurityCenter_sqlServerAdvancedDataSecurityMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_sqlManagedInstanceAdvancedDataSecurityMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_sqlServerAdvancedDataSecurityEmailsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_sqlManagedInstanceAdvancedDataSecurityEmailsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_sqlServerAdvancedDataSecurityEmailAdminsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_sqlManagedInstanceAdvancedDataSecurityEmailAdminsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_kubernetesServiceRbacEnabledMonitoringEffect="Audit"
EnableMonitoringinAzureSecurityCenter_kubernetesServicePspEnabledMonitoringEffect="Audit"
EnableMonitoringinAzureSecurityCenter_kubernetesServiceAuthorizedIPRangesEnabledMonitoringEffect="Audit"
EnableMonitoringinAzureSecurityCenter_kubernetesServiceVersionUpToDateMonitoringEffect="Audit"
EnableMonitoringinAzureSecurityCenter_vulnerabilityAssessmentOnManagedInstanceMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_vulnerabilityAssessmentOnServerMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_threatDetectionTypesOnManagedInstanceMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_threatDetectionTypesOnServerMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_adaptiveNetworkHardeningsMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_restrictAccessToManagementPortsMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_restrictAccessToAppServicesMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_disableIPForwardingMonitoringEffect="AuditIfNotExists"
EnableMonitoringinAzureSecurityCenter_ensureServerTDEIsEncryptedWithYourOwnKeyMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_ensureManagedInstanceTDEIsEncryptedWithYourOwnKeyMonitoringEffect="Disabled"
EnableMonitoringinAzureSecurityCenter_containerBenchmarkMonitoringEffect="AuditIfNotExists"

}

#build the resource group hash array
$rgArray = @{ ResourceGroup = $resourceGroupParams }